### ISSUE TITLE
Problem writing Nodes without Tags

### ISSUE THREAD

**Issue by petervansebille-tomtom** [woltapp/parallelpbf#8]
I'm writing a tool to create country-based PBF files from the planet.pbf using parallelpbf for both reading and writing.

When Nodes without tags are writing to the country PBF file, this results in a "corrupt" file. Meaning that PBF file consumers like Osmosis, jOSM but also parallelpbf cannot read.

When in my tool I add a dummy tag to Nodes that don't have a tag the output PBF files are correct.

I think the root cause is in https://github.com/woltapp/parallelpbf/blob/master/src/main/java/com/wolt/osm/parallelpbf/encoder/DenseNodesEncoder.java where it unconditionally adds the tag delimiter. That should most likely only happen when there are tags. At least, that's what I see in the Osmosis implementation.

**Comment by akashihi** [comment]
Actually the standard says: 

> Keys and values for all nodes are encoded as a single array of stringIDs. Each node's tags are encoded in alternating <keyid> <valid>. We use a single stringid of 0 to delimit when the tags of a node ends and the tags of the next node begin. The storage pattern is: ((<keyid> <valid>)* '0' )* **As an exception, if no node in the current block has any key/value pairs, this array does not contain any delimiters, but is simply empty**. 

As i understand, delimiters must present for each node if at least a single node has tags, but there shouldn't be any delimiters, if there are no nodes with tags in the block and i'm violating that requirement. 

This should be fixed with PR #9 , could you please verify that it solves your issue before i merge it?
